config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get "examples/css_variable" => "examples#css_variable"
  get "examples/video_player" => "examples#video_player"
  get "examples/drum_kit" => "examples#drum_kit"
  get "examples/local_tapas" => "examples#local_tapas"
  get "examples/type_head" => "examples#type_head"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  layout "examples"
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/views/examples/css_variable.html.erb
<div  class="css-variable">
  <div class="controls">
    <label for="spacing">Spacing:</label>
    <input data-controller="css-variable" data-action="css-variable#update mousemove->css-variable#update" id="spacing" type="range" name="spacing" min="10" max="200" value="10" data-css-variable-suffix="px">

    <label for="blur">Blur:</label>
    <input data-controller="css-variable" data-action="css-variable#update mousemove->css-variable#update" id="blur" type="range" name="blur" min="0" max="25" value="0" data-css-variable-suffix="px">

    <label for="base">Base Color</label>
    <input data-controller="css-variable" data-action="css-variable#update mousemove->css-variable#update" id="base" type="color" name="base" value="#ffc600">
  </div>
  <img id="image" src="https://source.unsplash.com/7bwQXzbF6KE/800x500">
</div>

<style>
  :root {
    --base: #ffc600;
    --spacing: 10px;
    --blur: 0px;
  }
</style>

app/views/examples/drum_kit.html.erb
<div data-controller="drum-kit" data-action="keydown@window->drum-kit#playSound" class="drum-kit">
  <div class="keys">
    <div data-key="65" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>A</kbd>
      <span class="sound">clap</span>
    </div>
    <div data-key="83" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>S</kbd>
      <span class="sound">hihat</span>
    </div>
    <div data-key="68" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>D</kbd>
      <span class="sound">kick</span>
    </div>
    <div data-key="70" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>F</kbd>
      <span class="sound">openhat</span>
    </div>
    <div data-key="71" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>G</kbd>
      <span class="sound">boom</span>
    </div>
    <div data-key="72" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>H</kbd>
      <span class="sound">ride</span>
    </div>
    <div data-key="74" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>J</kbd>
      <span class="sound">snare</span>
    </div>
    <div data-key="75" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>K</kbd>
      <span class="sound">tom</span>
    </div>
    <div data-key="76" data-action="transitionend->drum-kit#removeTransition" class="key">
      <kbd>L</kbd>
      <span class="sound">tink</span>
    </div>
  </div>

  <audio data-key="65" src="sounds/clap.wav"></audio>
  <audio data-key="83" src="sounds/hihat.wav"></audio>
  <audio data-key="68" src="sounds/kick.wav"></audio>
  <audio data-key="70" src="sounds/openhat.wav"></audio>
  <audio data-key="71" src="sounds/boom.wav"></audio>
  <audio data-key="72" src="sounds/ride.wav"></audio>
  <audio data-key="74" src="sounds/snare.wav"></audio>
  <audio data-key="75" src="sounds/tom.wav"></audio>
  <audio data-key="76" src="sounds/tink.wav"></audio>
</div>

app/views/examples/local_tapas.html.erb
<div data-controller="local-tapas" class="local-tapas">
  <div class="wrapper">
    <h2>LOCAL TAPAS</h2>
    <p></p>
    <ul class="plates" data-target="local-tapas.itemsList">
      <!-- <li>Loading Tapas...</li> -->
    </ul>
    <form class="add-items" data-target="local-tapas.form">
      <input data-target="local-tapas.input" type="text" name="item" placeholder="Item Name" required>
      <input data-action="local-tapas#submit" type="submit" value="+ Add Item">
    </form>
    <button data-action="local-tapas#clear" id="clear-list">Clear List</button>
  </div>
</div>

app/views/examples/type_head.html.erb
<div class="type-head">
  <form class="search-form" data-controller="type-head">
    <input data-action="keyup->type-head#autocomplete" data-target="type-head.input" type="text" class="search" placeholder="City or State">
    <ul class="suggestions" data-action="click->type-head#select" data-target="type-head.suggestions">
      <li>Filter for a city</li>
      <li>or a state</li>
    </ul>
  </form>
</div>

app/views/examples/video_player.html.erb
<div class="video-player">
  <div class="player" data-controller="video-player" data-target="videoplayerPlayer">
     <video data-target="video-player.video" data-action="click->video-player#togglePlay timeupdate->video-player#progressUpdate" src="https://player.vimeo.com/external/194837908.sd.mp4?s=c350076905b78c67f74d7ee39fdb4fef01d12420&profile_id=164" class="player__video viewer" ></video>
     <div class="player__controls">
       <div data-target="video-player.progress" data-action="click->video-player#scrub mousedown->video-player#mousedown mouseup->video-player#mouseup mousemove->video-player#mousemove" class="progress">
        <div data-target="video-player.progressBar" class="progress__filled"></div>
       </div>
       <button data-target="video-player.toggle" data-action="click->video-player#togglePlay" class="player__button toggle" title="Toggle Play">►</button>
       <input data-action="change->video-player#rangeUpdate mousemove->video-player#rangeUpdate" type="range" name="volume" class="player__slider" min="0" max="1" step="0.05" value="1" alt="Volume">
       <input data-action="change->video-player#rangeUpdate mousemove->video-player#rangeUpdate" type="range" name="playbackRate" class="player__slider" min="0.5" max="2" step="0.1" value="1">
       <button data-action="click->video-player#skip" data-skip="-10" class="player__button">« 10s</button>
       <button data-action="click->video-player#skip" data-skip="25" class="player__button">25s »</button>
     </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Javascript30 converted to Stimulus JS</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/examples.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Javascript30 converted to Stimulus JS</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag    'examples', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'examples', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-4">
  <h2 class="mb-4">Wes Bos Javascript30 examples converted to Stimulus JS</h2>
  <ol>
    <li><%= link_to "Drum Kit: handling keyboard events", examples_drum_kit_path %></li>
    <!-- <li><%#= link_to "CSS Variable: playying with CSS :root variable", examples_css_variable_path %></li> -->
    <li><%= link_to "Video Player: a custom HTML5 video player", examples_video_player_path %></li>
    <li><%= link_to "Local Tapas: yet another todo list example", examples_local_tapas_path %></li>
    <li><%= link_to "Type Head: small autocomplete search field", examples_type_head_path %></li>
  </ol>
</div>